### ISSUE TITLE
industrycat_10 assignment of Transport and Communication

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#106]
I wanted to highlight the assignment of the category `7` (`Transport and Communication`) and `8`  (`Financial and Business Services`) for versions based on ISIC4 (that is surveys from 2008 on for ENOE).

You currently have:

https://github.com/worldbank/gld/blob/275c82df16090143407e062f94536abf2ec926bb/GLD/MEX/MEX_2014_ENOE/MEX_2014_ENOE_v01_M_v01_A_GLD/Programs/MEX_2014_ENOE_V01_M_V01_A_GLD.do#L818-L832

That is, category `7` is only values coding values 49 to 53, which is the category `Transportation and storage`. The codes corresponding to `Information and communication` (codes 58 to 63) are assigned to the category `10` (`Other services, unspecified`). Similarly, category `8` includes real estate as well as professional, scientific, and technical activities (codes 68 to 75) which you also have as category Other.. This needs updating in all surveys.

Additionally, as a recommendation, I would suggest converting the first digits to integer (industrycat_isic needs to be string of length four, but your helpers can be what serves your best interest). I suggest the following which I find easier to read (but is a personal preference, so feel free to ignore this suggestion).

```
gen helper = substr(industrycat_isic, 1,2)
destring helper, replace
gen industrycat10 = .
[... other lines ...]
replace industrycat10 = 6 if inrange(helper, 45, 47) | inrange(helper, 55, 56) 
replace industrycat10 = 7 if inrange(helper, 49, 53) | inrange(helper, 58, 63) 
replace industrycat10 = 8 if inrange(helper, 64, 82)
replace industrycat10 = 9 if helper == 84
replace industrycat10 = 10 if inrange(helper, 85, 99)
[... other lines ...]
drop helper
```

**Comment by alexandraqn** [comment]
Thank you Mario for this, i will do the amendments in the groups, I think it would be a good idea to insert this recommendations in the guide of harmonisation since it seems we are interpreting the grouping differently.

**Comment by gronert-m** [comment]
Yes, that is a good point. It certainly needs to be included!

**Comment by alexandraqn** [comment]
Hi Mario,
I wonder if you meant section 6 for 45-47 and 55-56? .

**Comment by gronert-m** [comment]
Indeed I did! Thanks for pointing it out. I edited it to correct.

**Comment by alexandraqn** [comment]
Great, so I close this because I did the agreed changes. I understand there is an ongoing debate on this issue so I suggest to reopen if necessary.
