### ISSUE TITLE
Urban / Rural distinction in ENOE data

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#108]
The current coding for urban and rural (from what I saw it is in all years) seems to be incorrect. The data checks already alert to this as, for example, for 2005, the survey urbanization rate is 62% while the World Bank data is 76.3%.

The current code is as follows:

https://github.com/worldbank/gld/blob/24ba2bfff70a38a26dc5a15d9a593ac421dc9d0d/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L248-L257

That is, locations of at least 15,000 (`t_loc` is 1 or 2) are deemed urban, those with fewer are said to be rural. The official definition is that a locations with a population with fewer than 2,500 are rural (images below are from [the ENOE glossary](https://www.inegi.org.mx/app/glosario/default.html?p=ENOE15) and the [ENOE teaching resources](http://cuentame.inegi.org.mx/poblacion/rur_urb.aspx?tema=P) websites)

![image](https://user-images.githubusercontent.com/63501500/130828601-a6c982b5-b081-4d8d-8005-195dbb15f3e9.png)

![image](https://user-images.githubusercontent.com/63501500/130828645-585577ba-8c45-4679-8139-c69ca9f061f3.png)

If I run this, for 2014 I get an urbanization rate of 76.88% and for 2005 of 76.6%

![image](https://user-images.githubusercontent.com/63501500/130829333-1a654bbd-b676-4df6-b086-00598407525f.png)

This is a smaller increase than reported in the World Bank Data (where it goes from 76.3% to 78.9%, see image below), but is much closer to the reported numbers - and uses the official definition.

![image](https://user-images.githubusercontent.com/63501500/130828515-e060e943-833c-4d87-ad2a-36f23200a2ff.png)

Lastly, just to avoid confusion, note that - at least in 2005 - the "VIV" data set has a variable `ur` labelled as "Urbano/Rural", but as can be seen, this cuts across all locality sizes and would lead to even lower urbanization rates.

![image](https://user-images.githubusercontent.com/63501500/130830679-d2552f80-e9bc-4398-82a4-a59d6c2620f9.png)

In closing, the definition of `urban` (and indeed `urb` in I2D2, too) needs to change to be

```
*<_urban_> 
 	gen byte urban=.  
 	replace urban=1 if inrange(t_loc,1,3)
 	replace urban=0 if t_loc==4 
 	label var urban "Location is urban" 
 	la de lblurban 1 "Urban" 0 "Rural" 
 	label values urban lblurban 
 *</_urban_> 
```

**Comment by gronert-m** [comment]
Just as an update, during last Friday's joint meeting, @buscandoaverroes highlighted the search and change function on Atom, the code editor, which allows you to make changes to several `.do` files in one go. Since here it is always about changing just 

```
replace urban = 0 if t_loc == 3 
```

to

```
replace urban = 1 if t_loc == 3 
```

this would be perfectly suited for this. This is further linked to issue #109 @buscandoaverroes is it OK if @alexandraqn asks you about this?

**Comment by buscandoaverroes** [comment]
Sure, no problem!

**Comment by alexandraqn** [comment]
Hi All, 
thanks for the comments. I will proceed with the changes requested and upload ASAP. 
Best,
Alexandra
