### ISSUE TITLE
Update in filenaming convention

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#109]
A conversation with the team running Datalibweb has highlighted that file names need to be updated. 

I have updated the guidelines accordingly (in commit 4a1f0f4) requesting the name of

- harmonization `.do` files and
- harmonized `.dta` files

So for example a name like `MEX_2007_ENOE_V01_M_V01_A_GLD.dta` needs to change to `MEX_2007_ENOE_V01_M_V01_A_GLD_ALL.dta` where the `ALL` part is so the `query dlw, country() year() type(gld) mod(ALL)` command of datalibweb can correctly read the information contained in the name.

That is in the guidelines and the way forward. Thinking about now it is enough to only amend the `.dta` files. Since this is fairly mechanical, as I need to do this for Angelo's data I wrote a little program to automate the process. You [can find it in this gist](https://gist.github.com/gronert-m/3caeb0b42b33f11bf4f8bd4908d790d4), but we can talk about it tomorrow at the weekly meeting (or next week in the case of Alex, who is on leave for this meeting).

**Edit** 

We need to change the names from the start to both `.do` and `.dta` files.

**Comment by gronert-m** [comment]
** Update **

As pointed out by @Junying-T during the Friday meeting, in addition to the name of the `.do` and `.dta` file, the save command at the end of the `.do` file should reflect the name change, i.e., change from

```
save "`path_output'/CCC_YYYY_Survey_v01_M_v01_A_GMD.dta"
```
to
```
save "`path_output'/CCC_YYYY_Survey_v01_M_v01_A_GMD_ALL.dta"
```

One of the easiest ways is to use the search and replace option across several files in Atom (other text editors may have that capacity, too) proposed by @buscandoaverroes .

**Comment by buscandoaverroes** [comment]
FYI, the way to bring up the project search (to search across multiple files) is Command + Shift + F (This is not immediately obvious since there's no menu option!) https://flight-manual.atom.io/using-atom/sections/find-and-replace/

**Comment by alexandraqn** [comment]
Hi All, 
Thanks for coming with solutions to address this!. 
My side this is done in the server, I used atom. Please, let me know if this also needs to be done for the GitHub files.

**Comment by buscandoaverroes** [comment]
PHL files are renamed

**Comment by alexandraqn** [comment]
All done my side, closing this.

**Comment by alexandraqn** [comment]
Sorry, I did not notice that other people needed to complete their task. Reopening.

**Comment by Junying-T** [comment]
Done my side as well! I am now closing this issue.

**Comment by buscandoaverroes** [comment]
Just confirming that, the "v" in the filenames is lowercase: so it should be `v01` not `V01`? As in the example in the document? I may have typed as `V` elsewhere so before I fix I just want to confirm.
```
PHL_2016_LFS_v01_M_v01_A_GLD_ALL.do
PHL_2016_LFS_v01_M_v01_A_GLD_ALL.dta
```

**Comment by gronert-m** [comment]
Since everything else is upper case it should be upper, too. However, in the checks I have written to test for V or v. My feeling is that datalibweb also will pre clean filenames either to all lower or all upper.
