### ISSUE TITLE
Template for Survey Introduction

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#126]
Dear All,

I have created the [template for survey introduction](https://github.com/worldbank/gld/blob/develop-merge/Support/Templates/1.%20Introduction%20to%20%5BSurvey%20Acronym%5D.md). Please comment and add as necessary.

Brief note on the table. I brought it down to only year and sample sizes (leave as ** -- ** if there is no number of HHs, as in IDN) since this is the basic info that we ought to always have. Other details may be described elsewhere, condensed to the minimum so this also does not take too long. But happy to be persuaded (^_^).

**Comment by gronert-m** [comment]
Based on conversations with you guys I have updated the document to:

- Have questions marks in all questions, and
- Expand a bit the "Other noteworthy aspects" part to better convey how this ought to be structure.

Still happy to get more comments, kindly requested by COB tomorrow 8th of September so we may implement it.

**Comment by buscandoaverroes** [comment]
Is this an appropriate place to include a short, "external resources" section that might link to any relevant National Stats Office, Publicly-available codebooks/documentation, etc? 

Alternatively, this information could also be compiled centrally elsewhere.

**Comment by alexandraqn** [comment]
No further comments from my side.

**Comment by gronert-m** [comment]
> Is this an appropriate place to include a short, "external resources" section that might link to any relevant National Stats Office, Publicly-available codebooks/documentation, etc?
> 
> Alternatively, this information could also be compiled centrally elsewhere.

I would personally have included that in the section on "Where can the data be found?" as I see raw data, without any external resources, as you say, not really useful. In the case of India this was easy because the link to the site where the data is released has a tab on "Documentation" where you can find everything. Less clearly but similarly in Mexico, where Documentation and Microdata are two tabs on the same landing page (image at the end).

I guess it is a question of how much we want to pre-chew info for people, but I would just include the main links here. Other information for example for ISCO and ISIC correspondence tables can be added in the particular documents that cover this.

Would that work for you?

![image](https://user-images.githubusercontent.com/63501500/132664871-71305c93-7a1d-494a-9c83-7c85222029eb.png)

**Comment by buscandoaverroes** [comment]
Sure, that works!

**Comment by buscandoaverroes** [comment]
Hi everyone, I've come across an issue and a solution to it:

When creating links to other documentation files, you cannot use the permalink or any other web address. You must use this specific type of relative linking that I refer to [here](https://github.com/worldbank/gld/commit/b204b486657c8d759ddc2754d5c5b7c18e153685#r56377785) and in the updated template. Also copying here because it's actually quite simple. The files must be in the same directory (but we already agreed this would be the case) and, importantly, you have to write the link to the other documents like this
```
[name to show in link](exact_file_name_without_any_slashes.md)
// example 
[GLD code](GLD_Harmonization_Template.do)  
``` 

The reason is because when you copy the permalink or web address of the other markdown files, the link will be valid _only as long as those files stay on that branch_. But as soon as you merge or move that branch, or even edit the file again, the link will not work. [This post](https://github.blog/2013-01-31-relative-links-in-markup-files/) explains what happens behind the scenes: basically github will always know to go to the current branch.

**Comment by gronert-m** [comment]
@buscandoaverroes Thanks! I have updated the document also for the other file. You can use the `../` operand to go up a folder.

In the case of [our template](https://github.com/worldbank/gld/blob/develop-merge/Support/Templates/1.%20Introduction%20to%20%5BSurvey%20Acronym%5D.md) it is under `gld/Support/Templates` (of its branch) and the file connected to is `gld/Support/Country Survey Details/MEX/ENOE/Correspondence_NAICS_ISIC.md` so we need to go one up from `gld/Support/Templates` to `gld/Support` and then put the rest (`Country Survey Details/MEX/ENOE/Correspondence_NAICS_ISIC.md`).

The operand `../` does this moving up so the link is then `../Country%20Survey%20Details/MEX/ENOE/Correspondence_NAICS_ISIC.md` (Note that `%20` is to write out the spaces between words).

**Comment by buscandoaverroes** [comment]
Oh, great, this is good to know. Thanks @gronert-m

**Comment by gronert-m** [comment]
@alexandraqn @buscandoaverroes  @Junying-T  Thanks for all the comments! I **close this issue and see the template as operational**. If any changes need to be made, please raise a new issue or create a develop branch to make changes to the template.

**Comment by gronert-m** [comment]
@alexandraqn @buscandoaverroes  @Junying-T 

This is just to update you that I amended one of the template section titles from

> What is the significance level?

to

> What is the geographic significance level?

**Comment by buscandoaverroes** [comment]
thanks, I updated PHL

**Comment by alexandraqn** [comment]
Done.

**Comment by gronert-m** [comment]
I have realised this has been here for some time and is no longer an issue. Thus I move to close it. Please let me know if you think I should reopen it. Thanks!
