### ISSUE TITLE
Adding educat_orig

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#129]
As proposed by Tom, I have added the `educat_orig` (as the others are `educat#` and `educat_isced` went for this instead of `education_orig`). I have updated:

- The excel data dictionary,
- The GLD Guide,
- The GLD template, and
- The Quality checks

The variable is placed between `educat4` and `educat_isced`:

https://github.com/worldbank/gld/blob/6ec2eb06d33dbf7500d7bdb5448b89f2426edb26/Support/Templates/GLD_Harmonization_Template.do#L516-L534

Note that the rules (as explained in the guide, screenshot below) is that, if the matching can happen 1-1 (i.e., there is a single variable in the raw data that codes educational attainment, simply use that. If there are two or more variables that may be necessary, leave missing and make a note of it.

![image](https://user-images.githubusercontent.com/63501500/132496827-a92a55b0-bcc9-406e-b729-ef14c98eebc2.png)

Let me know of any questions you may have.

**Comment by alexandraqn** [comment]
Completed.

**Comment by buscandoaverroes** [comment]
Also completed for me in #130

**Comment by Junying-T** [comment]
Completed for ZAF and IDN.
