### ISSUE TITLE
Branch Naming

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#132]
As agreed in the meeting discussing GitFlow and [written in the guidelines](https://worldbank.github.io/gld/docs/branch_management/bm_index/) develop branches ought to bear only the three letter code of the country (e.g. THA for Thailand). Only if such a branch already exists and another branch for that same country (yet a different survey) is being coded simultaneously (unlikely but not impossible) should the branch be called "THA-[Survey Acronym]".

I have seen that the new branches for Indonesia and Turkey do not follow this structure. I remember this was a confusion at the start I discussed with @Junying-T but it seems to have had a know-on effect on @alexandraqn. I thus recommend we are strict with enforcing these rules and kindly ask you both to amend the names of your branches. 

Let me know of any questions.

**Comment by alexandraqn** [comment]
I apologize for that. I changed this. Thanks

**Comment by Junying-T** [comment]
Sorry I forgot to change the name. It's done and I am closing this issue.
