### ISSUE TITLE
Storage type confirmation for industrycat_isic and occup_isco

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#134]
Running the GLD quality checks, I noticed that `industrycat_isic` is [supposed to encoded as string ](https://github.com/worldbank/gld/blob/9cfdd0a9d6e2e13ce966fa028ff3fd65b5dca0d8/Support/Q%20Checks/Helper%20Programs/Helper_GLD_VarLists.do#L31) whereas `occup_isco` and `educat_isced` are both [defined as numeric](https://github.com/worldbank/gld/blob/9cfdd0a9d6e2e13ce966fa028ff3fd65b5dca0d8/Support/Q%20Checks/Helper%20Programs/Helper_GLD_VarLists.do#L25). 

This is not really a major issue but just wondering if there's a reason why the three are not all defined to be the same storage type. If they should all be the same storage type, then what type? Otherwise I'm happy to leave as is.

**Comment by gronert-m** [comment]
Yes, this is both in the data dictionary (images below) and the Guidelines. The reason for the separate treatment of ISIC is twofold. One is to offer the option to code the *Section*, which is the highest level order in ISIC (I believe only from Rev 3.1. onwards, but anyway) and is a single letter. The other reason is to ensure that all codes are of length 4. In ISCO all codes are 1 through 9 and then subcategories, i.,e., it could go from 1001 to 9999 (not all options used) and similarly for ISCED. 

For ISIC the next category under *Section* is *Division* and those are already two digits, from 01 to 99, so if you had a code `141` it is unclear whether it could be `0141 - Raising of cattle and buffaloes` of `1410 - Manufacture of wearing apparel, except fur apparel`, so we need zero padding for divisions 01 to 09, which makes it a string. For all others it is not a problem.


ISCED

![image](https://user-images.githubusercontent.com/63501500/132841977-3ab18262-8386-43f0-8daa-6f00dad61981.png)


ISIC

![image](https://user-images.githubusercontent.com/63501500/132842027-bd5f1e7e-4c32-40f1-98a1-c1280d3ad3d3.png)


ISCO

![image](https://user-images.githubusercontent.com/63501500/132842076-3f9c35c1-bac7-4300-a440-3b9914cdb87b.png)

**Comment by gronert-m** [comment]
@buscandoaverroes  Is this OK, for you? If year, please close the issue. Otherwise let me know. Thanks!

**Comment by buscandoaverroes** [comment]
Sure, I'll just link this to #142 since it looks like in the end we'll have to change all isco-related vars to string for record-keeping before closing
