### ISSUE TITLE
ISCO as string

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#142]
Hi to all,

In discussion with @buscandoaverroes I realise now that ISCO codes may need zero padding from the left. This is in the case of Armed Forces Occupations, that start with 01, 02, or 03. In order not to confuse 110 with 011 we need to have the occupation isco variables (`occup_isco occup_isco_2 occup_isco_year occup_isco_2_year`) as **a four digit string**. 

So a code 1 (Manager) will be `"1000"`, if no deeper information available. Code 11 (Chief Executives, Senior Officials and Legislators) will be `"1100"`, code 111 (Legislators and Senior Officials) will be `"1110"`, and finally code 1111 (Legislators) will be `"1111"`.

Code 31 (technically 031 for Armed Forces Occupations, Other Ranks) will be `"0310"`.

I apologize for the hassle this change causes, as you need to re-run your already completed GLD codes (no impact on I2D2) but these are the growing pains of the first round of this work and hopefully once we have set this up this should not happen again (-that often...).

I have updated already the data dictionary, GLD guidelines, GLD template, and quality check codes (commit bf73784).

Please post when you are done with this and the last to post kindly close the issue.

**Comment by buscandoaverroes** [comment]
This is completed for PHL in #143

**Comment by alexandraqn** [comment]
Hi Mario and all, 
Thanks very much for bringing this up. This was completed for MEX a few weeks ago. Since we have a new check I re run the checks already and they are in the server as requested.

**Comment by gronert-m** [comment]
I have updated the static q check code (commit 5420d7c) to correct a mistake. Thanks @alexandraqn for pointing this out!
