### ISSUE TITLE
Pad all 2-digit ISIC and ISCO data to 4 digits

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#157]
https://github.com/worldbank/gld/blob/6b8072f4431e0ee61cb9f254ff01129ccf85823e/Support/Q%20Checks/Helper%20Programs/GLD%20Static%20Q-Checks.do#L720-L733

Since it seems like many of us will have ISIC/ISCO codes in final GLD data that are 2 digits, is it worth changing 726 to something like 

```
qui : count if !inlist(check_isic_length,1,2,4,.) 
...
post `memhold' ("Labour") ("`var'") ("ISIC code is not of length 1 (Letter) 2 (digits), or 4 (digits) (number of cases ->)") (`r(N)') (1)
```

and for other relevant ISIC/ISCO variables also?

**Comment by gronert-m** [comment]
Thanks for raising this. **It should always be four digits** to ensure  to ensure different lengths do not need to be aligned. As stated in the dictionary and guide, for a two digit code simply add two zeroes after it, i.e., if you only have industry code 14 (Manufacture of wearing apparel in ISIC 4) it should be coded as `1400`.

If you only have 142 (Manufacture of articles of fur) it should be coded as `1420`. The same applies for occupation codes. Let me know of any questions you may have still.

**Comment by buscandoaverroes** [comment]
Sure, will address in #158
