### ISSUE TITLE
MEX population inconsistency

### ISSUE THREAD

**Issue by alexandraqn** [worldbank/gld#168]
ET proposed to check population size and population +15 size because it seems the initial estimation was off for over 1 000 000 in year 2020

After discussion with ET decided to re ran codes and amend the first section of the code.

**Comment by gronert-m** [comment]
Thanks @alexandraqn for going through it so meticulously! It is good to know we are matching their numbers. I think this is solved and thus I will close the issue. (Of course reopen if you need it).
