### ISSUE TITLE
Subnatid variables in do-file vs guide vs checks

### ISSUE THREAD

**Issue by alexandraqn** [worldbank/gld#240]
Hi @gronert-m ,

Please, can you clarify which is the correct specification of the subnatid variables. Are they string? 

The do-file template from main/gld/support folder says the following:

```stata

*<_subnatid1_>
/* <_subnatid1_note>
	The variable is string and country-specific categorical. Numeric entries are coded in string format using the following naming convention: “1 – Hatay”. That is, the variable itself is to be string, not a labelled numeric vector. 
	
	Example of entries would be "1 - Alaska",  "2 - Arkansas", ...
</_subnatid1_note> */
	gen str subnatid1 = ""
	label var subnatid1 "Subnational ID at First Administrative Level"
*</_subnatid1_>


*<_subnatid2_>
	gen str subnatid2 = ""
	label var subnatid2 "Subnational ID at Second Administrative Level"
*</_subnatid2_>


*<_subnatid3_>
	gen str subnatid3 = ""
	label var subnatid3 "Subnational ID at Third Administrative Level"
*</_subnatid3_>

```

source: https://github.com/worldbank/gld/blob/main/Support/C%20-%20Templates/GLD_Harmonization_Template.do

The guide from main/gld//support folder says the following: Also why you say string and then country-specific categorical?

```stata
/*The variable is string and country-specific categorical. 
Numeric entries are coded in string format using 
the following naming convention: “1 – Hatay”. 
That is, the variable itself is to be string, not a labelled numeric vector.*/
```
Source: version of 13 days ago https://github.com/worldbank/gld/blob/main/Support/A%20-%20Guides%20and%20Documentation/GLD_1.0_Guidelines.docx 

The quality checks (dynamic) from main/gld/support say the following:
 Here unfortunately due to problems with access to the server I can only say that when you ran de codes it brings a flag saying that the subnatid variables are string and this is not expected.  (the checks are ran for 2007 and 2006 EGY as an example in my server user)

https://github.com/worldbank/gld/tree/main/Support/D%20-%20Q%20Checks 
Thanks you very much for clarifying this.

Best,

Alexandra

**Comment by gronert-m** [comment]
Hi @alexandraqn,

Thanks for raising this. I have changed the checks code so it expects the subnatid variables to be string as in the template and manual. This is done in this commit:

https://github.com/worldbank/gld/commit/8c4c0fab6cc7508ed7311c6db86cc2064c4922cb

Let me know if that clears it up. Best,

Mario

**Comment by alexandraqn** [comment]
Hi @gronert-m,

Since I am still experiencing challenges with the VDI , I will only be able to confirm this later in the week probably. Thanks for changing this.

Best,

Alexandra

**Comment by alexandraqn** [comment]
Hi Mario, 
as my vdi is solved, I verified that this code is ok and solves the issue. 
Thanks.
