### ISSUE TITLE
Vocational training variable in INDIA EUE

### ISSUE THREAD

**Issue by giofsantos11** [worldbank/gld#29]
This issue is concerning the GLD variable called `vocational`, labelled as "ever received vocational training." To me, a straightforward variable equivalent in the India survey is `Vocational_Training` defined as "whether receiving or received any vocational training." However, there are a few years when this variable is not available.

There is also a variable in the EUE called `Technical_Education`, which seem more or less like a proxy for vocational training. In the year 1999, for instance, @gronert-m used this variable for `vocational` and that is what I did for the years when `Vocational_Training` variable is not present. 

However, in years when both variables are present, I noticed that they are a bit different as can be seen from the example below (from 2005 survey). For instance, 2889 people who reported receiving formal vocational training reported not receiving any technical education. 

My question is: do you think I should still use `Technical_Education` when `Vocational_Training` variable is not available considering that they seem to be quite different? Or should I leave the GLD variable, `vocational` missing when only `Technical_Education` is available? Or should I just consistently use `Technical_Education` for all years since this is consistently available? Not sure if I stated the problem clearly, but please feel free to ask for clarifications.

<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/angelogabriellesantos/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/angelogabriellesantos/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>

Education | Receive formal   vocational training | Received   vocational training: formal | Non-formal:   hereditary | Non-formal:   others | Did not receive   any vocational training | Total
-- | -- | -- | -- | -- | -- | --
Non technical education | 1,243 | 1,646 | 2,720 | 3,046 | 102,053 | 110,708
Technical degree in agri/engineering, etc. | 21 | 37 | 1 | 4 | 195 | 258
Diploma in agriculture | 6 | 10 | 1 | 0 | 24 | 41
Angineering/technology | 128 | 495 | 10 | 12 | 661 | 1,306
Medicine | 15 | 68 | 1 | 4 | 103 | 191
Crafts | 12 | 58 | 6 | 2 | 41 | 119
Other subjects | 105 | 334 | 8 | 38 | 480 | 965
diploma or certificate in agriculture | 1 | 10 | 0 | 0 | 6 | 17
Engineering/technology | 23 | 75 | 1 | 2 | 179 | 280
Medicine | 5 | 16 | 0 | 2 | 54 | 77
Crafts | 6 | 8 | 1 | 0 | 21 | 36
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
Total | 1,595 | 2,838 | 2,753 | 3,120 | 104,009 | 114,315

**Comment by gronert-m** [comment]
The image below shows an example of the 2005 (62nd round) questionnaire where both choices are available.

![Capture](https://user-images.githubusercontent.com/63501500/122778043-88693d80-d2a4-11eb-9cf9-78a3ecb94f9a.PNG)

The decision in the end was to only codify if the explicit vocational training question was raised, otherwise training module questions are left missing. If you agree with this, @giofsantos11 , please close the comment.

**Comment by giofsantos11** [comment]
Agree with this, @gronert-m . Will close this issue
