### ISSUE TITLE
[Correction]: PHL 2016 to 2019: Recoding of subnatid1

### ISSUE THREAD

**Issue by yannwbg** [worldbank/gld#445]
### Contact Details

ybourgeois@worldbank.org

### Survey Name

PHL_2016_LFS to PHL_2019_LFS

### What is the error?

Observations with **subnatid1** == **17** and **subnatid1** == **4** are not labelled. They should have been recoded to **41** and **42** respectively from what I understand and it looks like some were (at least in 2016).

### Relevant erroneus code

```shell
Don't know about the relevant code. The error I noticed is in the output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gronert-m** [comment]
@yannwbg Thanks for raising this. This is taken on and corrected in pull request #447
