### ISSUE TITLE
Duplicates in ZAF2020 QLFS Quarter 2

### ISSUE THREAD

**Issue by Junying-T** [worldbank/gld#48]
There are 668 duplicated observations (or 169 households) in quarter two of 2020, which might result from a coding error of the variable `UQNO`. They account for 0.32% of total sample size These observations cannot be uniquely defined by **household number** and **personal number** within quarter two, but most of them can be uniquely defined by **all variables**. 

```duplicates report _all```
![duplicates command output](https://user-images.githubusercontent.com/84488698/123875682-1b8b1e80-d908-11eb-963d-aea8c58c0df4.png)

In other words, only 5 observations out of all observations in the dataset are “truly” duplicated. These 5 observations have identical information for all variables. 
 
![duplicates tag](https://user-images.githubusercontent.com/84488698/123875939-850b2d00-d908-11eb-98c3-4552eabbae9b.png)

The others are “partially” duplicated. They have same `UQNO` and `PERSONNO` but in fact are referring to different individuals. Pointed out by Mario, gender, population group, and age are different for the same person (in terms of `PERSONNO`) in the same household as shown in the picture, taking household #199103740000006016 as an example. 
 
![image](https://user-images.githubusercontent.com/84488698/123876024-a53aec00-d908-11eb-8f39-6e3b97340b98.png)

It seems that lines 1047, 1050, and 1051 form one household, while 1048, 1049, 1052, and 1053 form another. If that is the case, then the codes of `UQNO` should be corrected.

**Comment by Junying-T** [comment]
Have reported this issue to Data First team and Stats SA. The temporary solution is to drop all **663** observations since they in fact are not duplicates and thus reflect different individuals' information but they have wrong `UQNO` or wrong `PERSONNO`. And we do not what the right codes for the two vars are. 

I kept one for each of the five "truly" duplicated observations. But this might be wrong, as we are not sure that the duplication does not caused by the same reason as the others.

**Comment by gronert-m** [comment]
@Junying-T  Thanks for documenting this. I agree with dropping them for now and see what answers you get from the South African counterparts. Keep an eye on the regional distribution of the drops. They are only 0.32% of the whole sample but from what I saw most of them are in KwaZulu-Natal in absolute terms and relatively most are in Western Cape, where it may be more then 0.5%. Still small but generally it is good ensure there is no particular bias happening.

**Comment by gronert-m** [comment]
@Junying-T  as the kind gentleman from Data First has addressed this in releasing v.2.1 of the Q2 data (you have already improved the world's data quality for all, btw!) I suggest you mention briefly what has happened, what the solution was and then close this issue.

**Comment by Junying-T** [comment]
It turned out that household IDs were changed when new variables, covid variables namely `Q510COMPANY` `Q511WORK` `Q512PLACE` `Q513PREVENT` `Q513BOTHER` `Q514RECEIVEPAY` `Q515FULLSALARY` `Q516SAMEJOB` `Q517LOSEJO`, were brought in. Thanks for Bruce McDougall's help, this problem has been fixed. Now *qlfs-2020-q2-worker-v2.1.dta* which is version 2.1 does not have any duplicated observations. ***Source of the file: https://www.datafirst.uct.ac.za/dataportal/index.php/catalog/829***
