### ISSUE TITLE
Bibliography/keeping track of links and public references

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#53]
A random thought/idea in my traveling to various links and documentation sites: does it make sense to have one centralized place to collect all of our key public/internet references and links, and then publish as a "Reference" document? Is this common practice or even a good idea anyway?

I'm not sure how one would do this, my only idea is to keep a [BibTeX file](https://bookdown.org/yihui/bookdown/citations.html) -- and I guess keep it on github -- and then add to along the way like another code file and render an output file when we need to. I've never done this, though. Thoughts? @gronert-m @alexandraqn @Junying-T @giofsantos11

**Comment by Junying-T** [comment]
Thanks for raising the issue, Tom! I think it's a good idea to compile all the public references together and keep updating the list. I feel it is important to categorize the links and keep them altogether at one place as I am now downloading all kinds of docs and papers for national industrial and occupational classifications. I just put the downloads to the "Doc" folder in the master data folder. And the corresponding links are spread in my notes. It's hard to get a full picture of those docs as they increases. I guess it is important to figure out a way to categorize the references, i.e. by country -  module - year?

**Comment by alexandraqn** [comment]
Hi Tom, 
This is actually a good idea. I understand that @gronert-m  is working towards a very good resource where we can guide users to references (web page). I wonder if the bibtex file could be a good resource for internal purposes. For sure it will help others understand where is everything coming from. 
Thanks for bringing this up!
-Alexandra
