### ISSUE TITLE
[Correction]: IND - nlfreason_year value labels mismatch

### ISSUE THREAD

**Issue by yannwbg** [worldbank/gld#593]
### Contact Details

ybourgeois@worldbank.org

### Survey Name

IND 1993, 2005, 2009 - 2022

### What is the error?

Depending on years (only checked between 1993 to 2022), nlfreason_year == 4 is sometimes labelled as "**Disabled**" and sometimes "**Disable**" 

### Relevant erroneus code

```shell
*<_nlfreason_year_>
	...
	label var nlfreason_year "Reason not in the labor force - 12 month recall"
	la de lblnlfreason_year 1 "Student" 2 "Housekeeper" 3 "Retired" 4 "Disable" 5 "Other"
	...
*</_nlfreason_year_>
```

### Updated code

```shell
*<_nlfreason_year_>
	...
	label var nlfreason_year "Reason not in the labor force - 12 month recall"
	la de lblnlfreason_year 1 "Student" 2 "Housekeeper" 3 "Retired" 4 "Disabled" 5 "Other"
	...
*</_nlfreason_year_>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gronert-m** [comment]
Dealth with for India in #595, must be in other places because at least the latest Template version had this type ("Disable" for nlfreason_year). #595 also updated the template.

Thanks for alerting me to this!
