### ISSUE TITLE
Comments on MEX 2005 GLD

### ISSUE THREAD

**Issue by gronert-m** [worldbank/gld#74]
@alexandraqn  I wanted to comment on the version you have created for MEX 2005 GLD that now incorporates the ISIC version after merging in the information from the NAICS-ISIC correspondance. I do it here because I can link to specific lines, which makes it visually clearer.

The first thing I wanted to point to is the repetition of the local `path_in`. as you can see below, `path_in` is defined in line 60 but then in line 70 and 72. This instances are not needed (if run all at a time - if you run a bit of the code from the do file, the next time you run something from there all previously created locals will have been wiped).

https://github.com/worldbank/gld/blob/07322ec6b5dbdfc658e717b9a409aa772f044826/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L60-L73

The second issue refers to the location of the file. As seen below lines 92 and 98 define where the the NAICS-ISIC file is read from. This should be `...\MEX_2005_ENOE\MEX_2005_ENOE_v01_M\Data\Stata`. Recall what we discussed yesterday, the INEGI excel file is to be under `Doc`, the `R` code that creates the `.dta` file under `Programs` and the output of the `R` code under `Data\Stata`. Furthermore, on the `GLD-Harmonization` system, please ensure that Stata files are under `Data\Stata` and not `Data\Original` - I think you have done it for all but 2005.

https://github.com/worldbank/gld/blob/07322ec6b5dbdfc658e717b9a409aa772f044826/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L88-L100

The third issue relates to the same place, in particular to lines 92 and 98 more in detail. The lines are:

https://github.com/worldbank/gld/blob/07322ec6b5dbdfc658e717b9a409aa772f044826/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L92

https://github.com/worldbank/gld/blob/07322ec6b5dbdfc658e717b9a409aa772f044826/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L98

Previously you have created `scian_1` by doing first `gen scian_1=p4a` and then `tostring scian_1, replace`. You can, by the way, do this in one command as `tostring p4a, gen(scian_1)`. So now you have on your master file variables `scian` and `scian_1`, while the NAICS-ISIC file contains variable `scian`. 

Your merge command `merge m:1 scian_1 using "file path", keep(match master)` does not work for me. Have you changed the `R` file so that `SCIAN_02_ISIC_3.1.dta` has a variable `scian_1` instead of `scian`? 

I propose the following, which did work for me:

```
*ISIC	
***first job
	rename scian scian_orig // get rid of the scian that was already there in the raw data
	tostring p4a, gen(scian)
	merge m:1 scian using "C:\Users\wb529026\OneDrive - WBG\Documents\Country Work\MEX\Industry Classification\SCIAN_02_ISIC_3.1.dta", keep(master match) nogen
	rename scian scian_1

***second job
	tostring p7c, gen(scian)
	merge m:1 scian using "C:\Users\wb529026\OneDrive - WBG\Documents\Country Work\MEX\Industry Classification\SCIAN_02_ISIC_3.1.dta", keep(master match) nogen
	rename scian scian_2
```

Note that my `using "path file"` here in the merge commands is also incorrect as the `SCIAN_02_ISIC_3.1.dta` file is not under `Data\Stata`.

While I am here, a final point on variable abbreviation. The definition of `male` is based on the original variable `sexo` which in your code is just `sex`. This works because Stata allows by default variable abbreviation.

https://github.com/worldbank/gld/blob/07322ec6b5dbdfc658e717b9a409aa772f044826/GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD.do#L345-L351

I think it is best to always reference the full variable. I can even imagine you wanted to type `sexo` but it just happened because you were typing quickly and this goes unnoticed because Stata is - inadvertently - making assumptions about what it thinks you meant. You should be in full control of this process.

Let me know of any questions you may have and thanks a bunch for this!

**Comment by alexandraqn** [comment]
Hi Mario,

Thank you so much for taking the time to look at the do-file. Indeed all the points you bring are valid specifically the comment about forgetting to call the files from the stata folder, I missed that because I was working from my one drive, I will fix it in all versions to avoid this issue again. Yesterday I ran into error messages every time I tried to generate using the string command with generate, and yes I did change the R code. 

Thanks very much for remind me about the positions of the files, it seems I forgot about it on my notes. I will act accordingly and let you know when I fix all the issues on this thread. 

Sincerely,
Alexandra

**Comment by alexandraqn** [comment]
Hi Mario,
So I fixed the issues you flagged. The only comment is that indeed "sex" referee to the gender. Yet in the raw data there is not such a variable called "sexo", the label of "sex" is "sexo" but the variable name is just "sex". In this survey the NSO abbreviated many variables names, so I decided not to rename them.  Apart from that, all other issues were fixed.
