### ISSUE TITLE
Change renv folder location 

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#76]
Figure out if/how this could be possible. Looks like there is a way to change the root paths of some items, but I can't tell if there's a way to change the root `renv` folder itself. See [this github issue ](https://github.com/rstudio/renv/issues/472) and the [vignette on path customization](https://rstudio.github.io/renv/reference/paths.html)

**Comment by buscandoaverroes** [comment]
also note that `renv::settings$snapshot.type("all")` then rerunning `renv::snapshot()` will ensure all packages are captured

**Comment by buscandoaverroes** [comment]
After a few attempts, I haven't found conclusive evidence that this is possible. Closing for now.

**Comment by kevinushey** [comment]
I'd be interested to know more why (in https://github.com/rstudio/renv/issues/472) you'd like to customize the location of the `renv` folder. Thanks!
