### ISSUE TITLE
Length of variable labels

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#88]
Hi @gronert-m @alexandraqn @Junying-T , my editor highlighted for me in red that some variable labels strings are longer than the specified maximum length (80 characters). This is coming from the newest version of the GLD template. I'm not sure what happens, but I think Stata just takes the first 80 characters. In any case, shouldn't we shorten them to 80 or fewer? What should they be? And I can change them in the template.

```
industrycat4                        "1 digit industry classification (Broad Economic Activities), primary job 7 day recall" // 85 chr
industrycat4_2                    "1 digit industry classification (Broad Economic Activities), secondary job 7 day recall" // 87 chr 
t_wage_nocompen_others "Annualized wage in all but primary & secondary jobs excl. bonuses, etc. 7 day recall" // 84 chr
industrycat4_year               "1 digit industry classification (Broad Economic Activities), primary job 12 month recall" // 88 chr
industrycat4_2_year           "1 digit industry classification (Broad Economic Activities), secondary job 12 month recall" // 90 chr
t_wage_nocompen_others_year "Annualized wage in all but primary & secondary jobs excl. bonuses, etc. 12 month recall)" // 88 chr

```

**Comment by gronert-m** [comment]
@buscandoaverroes Thank you for bringing this up. I have updated the text for all six cases in the develop-merge branch so they are below 80 chars.
